import { supabase } from './supabase'
import type { OwnProfile, PublicMediaPage, PublicProfileResponse } from '../types/profile'
function client() { if (!supabase) throw new Error('Supabase is not configured.'); return supabase }
export async function fetchOwnProfile(userId: string) { const { data, error } = await client().from('profiles').select('*').eq('user_id', userId).maybeSingle(); if (error) throw error; return data as OwnProfile | null }
export async function saveOwnProfile(profile: OwnProfile) { const { user_id, display_name, bio, avatar_url, external_links, is_public, show_library, show_favorites, show_stats } = profile; const { data, error } = await client().from('profiles').update({ display_name, bio, avatar_url, external_links, is_public, show_library, show_favorites, show_stats, updated_at: new Date().toISOString() }).eq('user_id', user_id).select('*').single(); if (error) throw error; return data as OwnProfile }
export async function claimUsername(username: string) { const { data, error } = await client().rpc('claim_profile_username', { p_username: username }); if (error) throw error; return data }
export async function setCustomListPublic(id: string, userId: string, isPublic: boolean) { const { error } = await client().from('custom_lists').update({ is_public: isPublic }).eq('id', id).eq('user_id', userId); if (error) throw error }
async function publicGet<T>(url: string, signal?: AbortSignal) { const response = await fetch(url, { signal, headers: { accept: 'application/json' } }); const data = await response.json() as T & { error?: string }; if (!response.ok) { const error = new Error(data.error || (response.status === 404 ? 'Profile not found or private.' : 'Public profile unavailable.')); Object.assign(error, { status: response.status }); throw error } return data }
export const fetchPublicProfile = (username: string, signal?: AbortSignal) => publicGet<PublicProfileResponse>(`/api/public/profile?username=${encodeURIComponent(username)}`, signal)
export const fetchPublicLibrary = (username: string, signal?: AbortSignal) => publicGet<PublicMediaPage>(`/api/public/library?username=${encodeURIComponent(username)}&limit=100&offset=0`, signal)
export const fetchPublicList = (username: string, slug: string, signal?: AbortSignal) => publicGet<PublicMediaPage>(`/api/public/list?username=${encodeURIComponent(username)}&slug=${encodeURIComponent(slug)}`, signal)
