import type { MediaItem } from '../src/types/media'

export const mediaItems: MediaItem[] = [
  {
    id: 'tmdb-1',
    externalId: '1',
    source: 'tmdb',
    title: 'First Feature',
    type: 'Movie',
    status: 'Watching',
    poster: '/first-poster.jpg',
    backdrop: '/first-backdrop.jpg',
    progress: '2025',
    year: '2025',
    rating: '8.4',
    description: 'The first title in the showcase.',
  },
  {
    id: 'tmdb-2',
    externalId: '2',
    source: 'tmdb',
    title: 'Second Feature',
    type: 'Movie',
    status: 'Planned',
    poster: '/second-poster.jpg',
    backdrop: '/second-backdrop.jpg',
    progress: '2024',
    year: '2024',
    rating: '7.9',
    description: 'The second title in the showcase.',
  },
  {
    id: 'tmdb-3',
    externalId: '3',
    source: 'tmdb',
    title: 'Anime Feature',
    type: 'Anime',
    status: 'Watched',
    poster: '/anime-poster.jpg',
    backdrop: '/anime-backdrop.jpg',
    progress: '2023',
    year: '2023',
    rating: '9.0',
    description: 'A completed anime title.',
  },
]
